# vi: sw=2 ts=2 sts=2 expandtab

language: python
os:
  - osx
  # Travis/osx doesn't support Python yet:
  #  see https://github.com/travis-ci/travis-ci/issues/2312
python:
  # - "2.6"  # no dictionary comprehensions in 2.6, sorry
  # - "3.2"   # waste of time, coverage module doesn't work
  - "3.6"
  # - "pypy"  # swig doesn't seem to work :(
matrix:
  fast_finish: true

before_install:
  - echo $TRAVIS_OS_NAME
  - pip install setuptools nose coverage coveralls

  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install swig; fi
install:
  - python setup.py build
  - python setup.py install

script: 
  # run tests from test directory itself to not get Box2D confused with
  # top-level dir
  - cd tests
  - nosetests -v -w . --with-coverage --cover-package=Box2D

after_success:
  - coveralls
